version: '2'
services:

  telegraf:
    image: telegraf
    pid: "host"
    network_mode: "host"
    privileged: true
    depends_on:
      - influxdb
    restart: always
    environment:
       - interval=60s
       - flush_interval=60s
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock

  influxdb:
    image: hypriot/rpi-influxdb
    ports:
      - "8082:8082"
      - "8086:8086"
      - "8089:8089"
    restart: always
    volumes:
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ./influxdb/data:/mnt/influxdb

  grafana:
    image: grafana/grafana
    ports:
       - "3000:3000"
    depends_on:
       - influxdb
    restart: always
    volumes:
      - ./grafana/config.ini:/etc/grafana/config.ini:ro
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards

  mariadb:
    image: jsurf/rpi-mariadb
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ~/mdbdata/mdb:/var/lib/mysql 
    environment:
      MYSQL_ROOT_PASSWORD: myRootPassword123
      MYSQL_DATABASE: myDb
      MYSQL_USER: myDbUser
      MYSQL_PASSWORD: myPassword123


